name: Project CI/CD Flow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v3  # Se utiliza la acción oficial de Docker para Build & Push
        with:
          context: .  # El directorio donde se encuentra tu Dockerfile
          file: Dockerfile  # Asegúrate de que el Dockerfile esté en la raíz o ajusta la ruta
          push: true  # Esto hace que se suba la imagen al repositorio Docker Hub
          tags: jhonnystr/docker-repo-java:latest  # Etiqueta para la imagen en Docker Hub
