name: Project CI/CD Flow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2  # Cambié a la versión v2
        with:
          java-version: '21'
          distribution: 'temurin'  # Ahora es compatible con la versión v2
          cache: 'maven'  # También compatible en v2

      - name: Build with Maven
        run: mvn clean install

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: jhonnystr/docker-repo-java
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
